export const BMIClassifications = {
  underweightClassification: {
    title: 'Você está abaixo do peso',
    text: `Para ganhar peso de forma saudável, é importante aumentar a ingestão calórica consumindo mais calorias do que você gasta. Inclua alimentos ricos em nutrientes e calorias, como abacate, nozes, sementes, queijos e azeite de oliva. Comer com mais frequência, fazendo várias refeições pequenas ao longo do dia, pode ajudar a aumentar a ingestão calórica sem se sentir muito cheio. <br><br>Incluir proteínas em todas as refeições é essencial para o crescimento muscular e a manutenção do corpo. Boas fontes de proteína incluem carnes magras, ovos, leite, queijo, leguminosas e nozes.<br><br>Além disso, escolher carboidratos complexos, como batata-doce, arroz integral, quinoa e aveia, fornece energia sustentada e são ricos em nutrientes. <br><br>Praticar exercícios de resistência, como levantamento de peso, pode ajudar a ganhar massa muscular, contribuindo para um ganho de peso saudável. <br><br>Evite calorias vazias, como alimentos ricos em açúcar e gordura saturada, como refrigerantes, doces e frituras, pois eles podem levar a problemas de saúde sem fornecer os nutrientes necessários. <br><br>Manter-se bem hidratado é importante, mas evite beber grandes quantidades de água antes das refeições para não reduzir o apetite. Por fim, consultar um profissional de saúde, como um nutricionista, pode ajudar a criar um plano alimentar personalizado e garantir que você está ganhando peso de forma saudável.`,
  },

  normalWeightClassification: {
    title: 'Você está com o peso normal',
    text: `Para manter um peso normal e uma boa saúde, é importante adotar uma alimentação balanceada, optando por uma dieta rica em frutas, vegetais, proteínas magras e grãos integrais. Evite alimentos processados e ricos em gordura saturada. <br><br>Além disso, beba pelo menos 1,5 litros de água por dia para manter-se hidratado. A prática regular de atividade física é fundamental. Exercícios como caminhadas, corridas, natação ou treinamento de resistência são ótimas opções. Tente ser ativo no dia a dia, usando escadas em vez de elevadores e caminhando mais. <br><br>Garantir um sono de qualidade também é crucial. Durma de 7 a 9 horas por noite para assegurar uma boa recuperação e saúde geral. <br><br>Evite substâncias nocivas, reduzindo ou evitando o consumo de álcool e não fumando. Por fim, é importante realizar consultas regulares com um médico e um nutricionista para monitorar sua saúde e ajustar sua dieta e rotina de exercícios conforme necessário. <br><br>Manter esses hábitos ajudará a garantir que você continue saudável e com um peso adequado.`,
  },

  overweightClassification: {
    title: 'Você está com sobrepeso',
    text: `Se você está com sobrepeso, adotar hábitos saudáveis pode fazer uma grande diferença na sua saúde e bem-estar. Primeiramente, é essencial reeducar sua alimentação. Opte por uma dieta rica em frutas, vegetais, proteínas magras e grãos integrais. Evite alimentos processados e ricos em gordura saturada, pois eles podem contribuir para o ganho de peso e outros problemas de saúde. <br><br>Além disso, beber bastante água, pelo menos 1,5 litros por dia, é fundamental para manter-se hidratado e ajudar no controle do apetite. A prática regular de exercícios físicos é igualmente importante. Atividades como caminhadas, corridas leves, ciclismo e natação são ótimas opções para começar.<br><br> Além disso, o treinamento de força, como levantamento de peso, pode ajudar a aumentar a massa muscular e acelerar o metabolismo. Tente ser ativo no dia a dia, incorporando mais movimento em suas rotinas, como usar escadas em vez de elevadores e caminhar mais. <br><br>Garantir um sono de qualidade também é crucial. Dormir de 7 a 9 horas por noite ajuda na recuperação do corpo e na manutenção de um metabolismo saudável. <br><br>Evitar substâncias nocivas, como o álcool e o tabaco, também é importante, pois elas podem afetar negativamente sua saúde e dificultar a perda de peso. <br><br>Consultar profissionais de saúde regularmente pode fornecer o suporte necessário para alcançar seus objetivos. Um médico pode monitorar sua saúde geral, enquanto um nutricionista pode ajudar a criar um plano alimentar personalizado. Se necessário, um psicólogo pode oferecer suporte emocional e ajudar a lidar com questões relacionadas ao peso. Adotar essas práticas pode ajudar a alcançar e manter um peso saudável, melhorando sua qualidade de vida e bem-estar geral. `,
  },

  obesityClassOneClassification: {
    title: 'Você está com Obesidade Grau 1',
    text: `Se você está com obesidade grau 1, é importante adotar hábitos saudáveis para melhorar sua saúde e reduzir os riscos associados. Primeiramente, foque em uma alimentação saudável e balanceada. Opte por uma dieta rica em frutas, vegetais, grãos integrais e proteínas magras. Evite alimentos processados, ricos em gordura e açúcar, pois eles podem contribuir para o ganho de peso e outros problemas de saúde. <br><br>A prática regular de atividade física é essencial. Exercícios como caminhadas, corridas leves, ciclismo e natação são ótimas opções. Além disso, o treinamento de força, como levantamento de peso, pode ajudar a aumentar a massa muscular e acelerar o metabolismo. Tente ser ativo no dia a dia, incorporando mais movimento em suas rotinas, como usar escadas em vez de elevadores e caminhar mais. <br><br>Garantir um sono de qualidade também é crucial. Dormir de 7 a 9 horas por noite ajuda na recuperação do corpo e na manutenção de um metabolismo saudável. Evitar substâncias nocivas, como o álcool e o tabaco, também é importante, pois elas podem afetar negativamente sua saúde e dificultar a perda de peso. <br><br>Consultar profissionais de saúde regularmente pode fornecer o suporte necessário para alcançar seus objetivos. Um médico pode monitorar sua saúde geral, enquanto um nutricionista pode ajudar a criar um plano alimentar personalizado. Se necessário, um psicólogo pode oferecer suporte emocional e ajudar a lidar com questões relacionadas ao peso. Adotar essas práticas pode ajudar a alcançar e manter um peso saudável, melhorando sua qualidade de vida e bem-estar geral.`,
  },

  obesityClassTwoClassification: {
    title: 'Você está com Obesidade Grau 3',
    text: `Se você está com obesidade grau 2, é fundamental adotar hábitos saudáveis para melhorar sua saúde e reduzir os riscos associados. Primeiramente, foque em uma alimentação equilibrada e nutritiva. Opte por uma dieta rica em frutas, vegetais, proteínas magras e grãos integrais, evitando alimentos processados e ricos em gordura saturada. Beber pelo menos 1,5 litros de água por dia é essencial para manter-se hidratado e ajudar no controle do apetite.<br><br> A prática regular de atividade física é crucial. Exercícios como caminhadas, corridas leves, ciclismo e natação são ótimas opções para começar. Além disso, o treinamento de força, como levantamento de peso, pode ajudar a aumentar a massa muscular e acelerar o metabolismo. Tente ser ativo no dia a dia, incorporando mais movimento em suas rotinas, como usar escadas em vez de elevadores e caminhar mais. <br><br>Garantir um sono de qualidade também é muito importante. Dormir de 7 a 9 horas por noite ajuda na recuperação do corpo e na manutenção de um metabolismo saudável. Evitar substâncias nocivas, como o álcool e o tabaco, também é essencial, pois elas podem afetar negativamente sua saúde e dificultar a perda de peso. <br><br>Consultar profissionais de saúde regularmente pode fornecer o suporte necessário para alcançar seus objetivos. Um médico pode monitorar sua saúde geral e prescrever tratamentos adequados, enquanto um nutricionista pode ajudar a criar um plano alimentar personalizado. Se necessário, um psicólogo pode oferecer suporte emocional e ajudar a lidar com questões relacionadas ao peso. Adotar essas práticas pode ajudar a alcançar e manter um peso saudável, melhorando sua qualidade de vida e bem-estar geral.`,
  },

  obesityClassThreeClassification: {
    title: 'Você está com Obesidade Grau 3',
    text: `Se você está com obesidade grau 3, também conhecida como obesidade mórbida, é crucial adotar hábitos saudáveis para melhorar sua saúde e reduzir os riscos associados. Primeiramente, foque em uma alimentação equilibrada e nutritiva. Opte por uma dieta rica em frutas, vegetais, proteínas magras e grãos integrais, evitando alimentos processados e ricos em gordura saturada. Beber pelo menos 1,5 litros de água por dia é essencial para manter-se hidratado e ajudar no controle do apetite. <br><br>A prática regular de atividade física é fundamental. Exercícios como caminhadas, corridas leves, ciclismo e natação são ótimas opções para começar. Além disso, o treinamento de força, como levantamento de peso, pode ajudar a aumentar a massa muscular e acelerar o metabolismo. Tente ser ativo no dia a dia, incorporando mais movimento em suas rotinas, como usar escadas em vez de elevadores e caminhar mais. <br><br>Garantir um sono de qualidade também é muito importante. Dormir de 7 a 9 horas por noite ajuda na recuperação do corpo e na manutenção de um metabolismo saudável. <br><br>Evitar substâncias nocivas, como o álcool e o tabaco, também é essencial, pois elas podem afetar negativamente sua saúde e dificultar a perda de peso. <br><br>Consultar profissionais de saúde regularmente pode fornecer o suporte necessário para alcançar seus objetivos. Um médico pode monitorar sua saúde geral e prescrever tratamentos adequados, enquanto um nutricionista pode ajudar a criar um plano alimentar personalizado. Se necessário, um psicólogo pode oferecer suporte emocional e ajudar a lidar com questões relacionadas ao peso. Adotar essas práticas pode ajudar a alcançar e manter um peso saudável, melhorando sua qualidade de vida e bem-estar geral.`,
  },
};
